categories:
- Data Managers
- Metagenomics
description: Data managers for CheckV reference data
homepage_url: https://bitbucket.org/berkeleylab/checkv/
long_description: Data managers for CheckV reference data
name: checkv_build_database
owner: ufz
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/data_managers/data_manager_checkv
type: unrestricted
