name: Assign Material Parameter
owner: ufz
description: Assign material parameters to a VTK Unstructured Grid based on a CSV file.
long_description: |
    This tool processes unstructured grid files and calculates specific properties such as permeability and mass flux within the grid.
categories:
- Molecular Dynamics
remote_repository_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
homepage_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: Assign material parameters to a VTK Unstructured Grid based on a CSV file.
suite:
  name: Assign Material Parameter
  description: Assign material parameters to a VTK Unstructured Grid based on a CSV file.
  long_description: |
      This tool processes unstructured grid files and calculates specific properties such as permeability and mass flux within the grid.