name: lm_get_projects
owner: wurz
description: This tool quries the Lambda-Miner database for the users projects
remote_repository_url: https://github.com/jw44lavo/galaxy-tools/blob/bgo/tools/bgo_tools/get_projects/
type: unrestricted
