name: suite_ogs_tools
owner: ufz
description: Various Tools for OpenGeoSys
long_description: |
    Aggregate Timings:                    Converts .json to .csv data.
    Assign Material Parameter:            Assign material parameters to a VTK Unstructured Grid based on a CSV file.
    Compute Time Shares:                  This tool processes a log file, extracts time data, and outputs the cumulative values. Optionally, the output can also be saved in JSON format.
    Map Boundary To Bulk:                 This tool maps the nodes of a boundary mesh to the corresponding nodes of a bulk mesh. 
                                            The output is a mesh with a `bulk_node_ids` field, which can be used in OGS for specifying inhomogeneous boundary conditions.
    Merge Data Arrays:                    Merges two scalar arrays into a 2D vector array in a VTU file.
    Merge Data Arrays Into One:           Merges multiple cell data arrays into a single cell data array in a VTU file.
    Merge Prefixed Arrays:                This tool processes tensor data from a VTU file, reconstructing the tensor field based on the specified dimension (2D or 3D).
    Prepare Inhomogeneous Mass Flux BC:   Generate an inhomogeneous node-based mass flux field along a slice through a mesh.
    Prepare Inhomogeneous Permeability:   Computes the effective permeability and mass flux for a given mesh. The script uses provided CSV profiles for permeability and velocity,
                                            calculates the properties, and adds them to the mesh.
categories:
- Assembly
remote_repository_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
homepage_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: Various Tools for OpenGeoSys
suite:
  name: OGS Tools
  description: Various Tools for OpenGeoSys
  long_description: |
      Aggregate Timings:                    Converts .json to .csv data.
      Material Parameter:            Assign material parameters to a VTK Unstructured Grid based on a CSV file.
      Compute Time Shares:                  This tool processes a log file, extracts time data, and outputs the cumulative values. Optionally, the output can also be saved in JSON format.
      Map Boundary To Bulk:                 This tool maps the nodes of a boundary mesh to the corresponding nodes of a bulk mesh. 
                                            The output is a mesh with a `bulk_node_ids` field, which can be used in OGS for specifying inhomogeneous boundary conditions.
      Merge Data Arrays:                    Merges two scalar arrays into a 2D vector array in a VTU file.
      Merge Data Arrays Into One:           Merges multiple cell data arrays into a single cell data array in a VTU file.
      Merge Prefixed Arrays:                This tool processes tensor data from a VTU file, reconstructing the tensor field based on the specified dimension (2D or 3D).
      Prepare Inhomogeneous Mass Flux BC:   Generate an inhomogeneous node-based mass flux field along a slice through a mesh.
      Prepare Inhomogeneous Permeability:   Computes the effective permeability and mass flux for a given mesh. The script uses provided CSV profiles for permeability and velocity,
                                            calculates the properties, and adds them to the mesh.