name: Prepare Inhomogeneous Permeability
owner: ufz
description: Computes the effective permeability and mass flux for a given mesh. The script uses provided CSV profiles for permeability and velocity,
        calculates the properties, and adds them to the mesh.
long_description: |
    Computes the effective permeability and mass flux for a given mesh. The script uses provided CSV profiles for permeability and velocity,
        calculates the properties, and adds them to the mesh.
categories:
- Molecular Dynamics
remote_repository_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
homepage_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: Computes the effective permeability and mass flux for a given mesh. The script uses provided CSV profiles for permeability and velocity,
        calculates the properties, and adds them to the mesh.
suite:
  name: Prepare Inhomogeneous Permeability
  description: Computes the effective permeability and mass flux for a given mesh. The script uses provided CSV profiles for permeability and velocity,
        calculates the properties, and adds them to the mesh.
  long_description: |
      Computes the effective permeability and mass flux for a given mesh. The script uses provided CSV profiles for permeability and velocity,
        calculates the properties, and adds them to the mesh.