name: data_manager_dada2
owner: matthias
description: "Data manager to download DADA2 reference databases"
homepage_url: "https://benjjneb.github.io"
long_description: |
  DADA2: Fast and accurate sample inference from amplicon data with single-nucleotide resolution
remote_repository_url: "https://github.com/bernt-matthias/mb-galaxy-tools/tree/master/data_managers/data_manager_dada2"
type: unrestricted
categories:
- Data Managers
