categories: 
- Tool Dependency Packages
description: A tool that just fails
homepage_url: https://github.com/bernt-matthias/mb-galaxy-tools/tree/master/tools/fail
name: fail
owner: mbernt
remote_repository_url: https://github.com/bernt-matthias/mb-galaxy-tools/tree/master/tools/fail
exclude:
- exclude.txt
- exclude2.txt
