categories:
- Data Managers
description: Megan tools data manager.
homepage_url: ''
long_description: ''
name: data_manager_megan_tools
owner: mbernt
remote_repository_url: https://github.com/bernt-matthias/mb-galaxy-tools/tree/master/data_managers/data_manager_megan_tools
type: unrestricted
