categories:
  - Ecology
description: A  tool for analyzing and visualizing the relationship between various doses and their corresponding biological responses 
long_description: The Tool analyze, and visualize the relationship between different doses of a substance and their corresponding biological or pharmacological responses.
name: dose_response_analysis_tool
owner: ufz
homepage_url: https://github.com/bernt-matthias/mb-galaxy-tools
remote_repository_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/tox_tools/dose_responses
