categories:
  - Ecology
  - Text Manipulation
description: Toxicity prediction using QSAR models
long_description: Toxicity prediction using QSAR models. Possible to select pre-defined models as well as user inputs.
name: Dose Response Curve for Toxicological Risk Assessement
owner: ufz
homepage_url: https://github.com/bernt-matthias/mb-galaxy-tools
remote_repository_url: https://github.com/bernt-matthias/mb-galaxy-tools/tools/tox_tools/baseline_calculator
