categories: [Metagenomics]
description: clusters metagenomic contigs into bins
homepage_url: https://downloads.jbei.org/data/microbial_communities/MaxBin/MaxBin.html
name: maxbin2
owner: matthias
remote_repository_url: https://github.com/bernt-matthias/mb-galaxy-tools.git
