categories:
- Data Managers
- Metagenomics
description: Data managers for geNomad reference data
homepage_url: https://github.com/apcamargo/genomad/
long_description: Data managers for geNomad reference data
name: genomad_build_database
owner: ufz
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/data_managers/data_manager_genomad
type: unrestricted
