categories:
- Data Managers
- Metagenomics
description: Data managers for virsorter reference data
homepage_url: https://github.com/jiarong/VirSorter2
long_description: Data managers for virsorter reference data
name: virsorter_build_database
owner: ufz
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/data_managers/data_manager_virsorter
type: unrestricted
