categories:
- Metagenomics
description: Phage host interaction toolkit report generator
long_description: |
  Create a report for the  Phage host interaction toolkit workflow
name: phi_toolkit_report
owner: ufz
homepage_url: https://git.ufz.de/borimcor/phage-host-analysis
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/tools/phi-toolkit
type: unrestricted
