name: sleepwaste
owner: mbernt
description: sleepwaste
long_description: |
  Waste time and memory
categories:
- Text Manipulation
homepage_url: https://github.com/bernt-matthias/mb-galaxy-tools/tree/master/tools/sleepwaste
remote_repository_url: https://github.com/bernt-matthias/mb-galaxy-tools/tree/master/tools/sleepwaster/
type: unrestricted