categories:
- Data Managers
- Metagenomics
description: Data managers for PhaBOX reference data
homepage_url: https://github.com/KennthShang/PhaBOX
long_description: Data managers for PhaBOX reference data
name: phabox_build_database
owner: ufz
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/data_managers/data_manager_phabox
type: unrestricted
