name: Merge Prefixed Arrays 
owner: ufz
description: This tool processes tensor data from a VTU file, reconstructing the tensor field based on the specified dimension (2D or 3D).
long_description: |
    This tool processes tensor data from a VTU file. It reconstructs the tensor field using the specified dimension (2D or 3D) and saves the updated VTU file.
categories:
- Assembly
remote_repository_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
homepage_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: This tool processes tensor data from a VTU file. It reconstructs the tensor field using the specified dimension (2D or 3D) and saves the updated VTU file.
suite:
  name: Merge Prefixed Arrays 
  description: This tool processes tensor data from a VTU file, reconstructing the tensor field based on the specified dimension (2D or 3D).
  long_description: |
      This tool processes tensor data from a VTU file. It reconstructs the tensor field using the specified dimension (2D or 3D) and saves the updated VTU file.