categories:
  - Text Manipulation
description: Create an archieve file from a collection
long_description: Collects the selected input files into a single ZIP archive, keeping only those whose file name matches the given pattern.
name: zipping
owner: ufz
homepage_url: https://github.com/Helmholtz-UFZ/galaxy-tools
remote_repository_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/utility
