categories:
  - Text Manipulation
description: Convert an xlsx file to a tabular
long_description: Extract one sheet from an xlsx/xls file and convert it to a tabular format
name: Excel to Tabular
owner: ufz
homepage_url: https://github.com/bernt-matthias/mb-galaxy-tools
remote_repository_url: https://github.com/bernt-matthias/mb-galaxy-tools/tools/tox_tools/baseline_calculator
