categories:
- Statistics
description: Execute R scripts
homepage_url: https://www.r-project.org/
long_description: |
  The tool is supposed to be used to execute tiny single-use R scripts.
name: r_tidyverse
owner: mbernt
remote_repository_url: https://github.com/bernt-matthias/mb-galaxy-tools/tree/master/tools/r/
type: unrestricted
