categories:
- Metagenomics
description: Identify virus and plasmid genomes from nucleotide sequences
name: genomad
owner: ufz
homepage_url: https://github.com/apcamargo/genomad/
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/tools/longorf/
type: unrestricted
