categories:
- Metagenomics
description: Identify virus and plasmid genomes from nucleotide sequences
long_description: |
  geNomad is a tool that identifies virus and plasmid genomes from nucleotide sequences. It provides state-of-the-art classification performance and can be used to quickly find mobile genetic elements from genomes, metagenomes, or metatranscriptomes.
name: genomad
owner: ufz
homepage_url: https://github.com/apcamargo/genomad/
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/tools/longorf/
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for geNomad function: {{ tool_name }}."
suite:
  name: "suite_genomad"
  description: "A suite of tools that brings the geNomad project into Galaxy."
  long_description: |
    geNomad is a tool that identifies virus and plasmid genomes from nucleotide sequences. It provides state-of-the-art classification performance and can be used to quickly find mobile genetic elements from genomes, metagenomes, or metatranscriptomes.
