categories:
- Imaging
name: omero_upload
description: Import images to an OMERO instance
long_description: Import images to an OMERO.server from Galaxy
owner: ufz
remote_repository_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/omero/omero_basic_upload
homepage_url: https://github.com/ome/omero-py/
exclude:
- omero-docker-compose.yml