categories:
- Imaging
name: omero_upload
description: Import images, region of interest, metadata into an OMERO.server using omero-py
long_description: Tool to import and link different objects into OMERO
owner: ufz
remote_repository_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/omero
homepage_url: https://github.com/ome/omero-py/
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper command line tools of the omero-py and ezomero package: {{ tool_name }}."
suite:
  name: "suite_omero_py"
  description: "A suite of tools that brings the omero-py and ezomero project into Galaxy."
  long_description: |
    OMERO.py provides an interface to the OMERO.blitz server.
