categories: [Sequence Analysis]
description: Search in fasta for regexp match
homepage_url: https://github.com/dariober/bioinformatics-cafe/tree/master/fastaRegexFinder
name: fasta_regex_finder
owner: matthias-bernt
remote_repository_url: https://github.com/bernt-matthias/mb-galaxy-tools.git
