categories:
- Data Managers
- Metagenomics
description: Data managers for vibrant reference data
homepage_url: https://github.com/AnantharamanLab/VIBRANT/
long_description: Data managers for vibrant reference data
name: vibrant_build_database
owner: ufz
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/data_managers/data_manager_vibrant
type: unrestricted
