categories:
- Imaging
description: Upload images to an OMERO instance
name: omero_upload
owner: mbernt
remote_repository_url: https://github.com/ome/omero-py/
type: unrestricted
exclude:
- omero-docker-compose.yml