categories:
- Sequence Analysis
description: obtain longest ORF in six-frame translations
name: longorf
owner: mbernt
remote_repository_url: https://github.com/bernt-matthias/mb-galaxy-tools/blob/master/tools/longorf/
type: unrestricted
