name: Map Boundary To Bulk
owner: ufz
description: This tool maps the nodes of a boundary mesh to the corresponding nodes of a bulk mesh. 
        
long_description: |
    This tool maps the nodes of a boundary mesh to the corresponding nodes of a bulk mesh. It reads two VTU files, one for the boundary mesh and one for the bulk mesh, and adds a nodal field to the boundary mesh to indicate which bulk mesh nodes correspond to each boundary node.
categories:
- Assembly
remote_repository_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
homepage_url: https://github.com/Helmholtz-UFZ/galaxy-tools/tree/main/tools/ogs-tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: This tool maps the nodes of a boundary mesh to the corresponding nodes of a bulk mesh. 
suite:
  name: Map Boundary To Bulk
  description: This tool maps the nodes of a boundary mesh to the corresponding nodes of a bulk mesh. 
        
  long_description: |
      This tool maps the nodes of a boundary mesh to the corresponding nodes of a bulk mesh. It reads two VTU files, one for the boundary mesh and one for the bulk mesh, and adds a nodal field to the boundary mesh to indicate which bulk mesh nodes correspond to each boundary node.