categories:
- Data Managers
description: Install DFAST databases
long_description: |
  This data managers fetches data for DFAST
name: data_manager_dfast
owner: ufz
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/main/data_managers/data_manager_dfast
homepage_url: https://github.com/galaxyproject/tools-iuc/
type: unrestricted
