categories:
- Proteomics
description: Labeled protein identification
long_description: |
  Labeled protein identification
name: sipros
owner: ufz
homepage_url: https://github.com/thepanlab/sipros5/
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/tools/sipros
type: unrestricted
