categories:
- Data Managers
- Metagenomics
description: Data managers for iPHoP reference data
homepage_url: https://bitbucket.org/srouxjgi/iphop
long_description: Data managers for iPHoP reference data
name: iphop_build_database
owner: ufz
remote_repository_url: https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/blob/main/data_managers/data_manager_iphop
type: unrestricted
